eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://localhost:9191/eureka/

management.endpoints.web.exposure.include: '*'

logging.level:
  .: INFO
  org.springframework: ERROR