spring:
  application:
    name: aurora

server:
  port: 9595
  session.cookie.name: UISESSION

security:
  basic.enabled: false
  oauth2:
    client:
      clientId: foo
      clientSecret: bar
      accessTokenUri: http://localhost:9191/auth/oauth/token
      userAuthorizationUri: http://localhost:9191/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:9191/auth/user/me

logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO